app/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    # path('',views.view_list, name='view_list'),
    path('', Baselist.as_view(), name = 'base_list'),
    path('help/', Helplist.as_view(), name = 'help_list'),
    path('get/', SSIList.as_view(), name = 'ssi_list'),
    path("get/ssi_detail/<slug:ssi>/", SSIDetail.as_view(), name="ssi_detail"),
    path('get/measure/<slug:meas_name>/<slug:ssi_name>/', MeasuresData.as_view(), name="name_meas"),
    path('get/remove_from_que/<slug:name_remove>/', Remove_from_que.as_view(), name = 'ssi_remove'),
    path('get/remove_from_measure/<slug:name>/<slug:ssiname>/', Remove_from_measure.as_view(), name = 'measure_remove'),
    path('get/make_measures/', views.make_measures, name = 'make_measures'),
    path('get/meastype_info/<slug:mt_name>/<slug:ssi_info_name>/<slug:id_measure>/', Meas_info.as_view(), name = 'meas_info'),
    path('create_SSI', views.ssi_new, name = 'create'),
    path('editssi/<slug:id_ssi>/', views.edit_SSI, name = 'edit_ssi'),
    path('remove_from_ssilist/<slug:id_name>/', Remove_from_ssilist.as_view(), name = 'ssi_remove_ssilist'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # path('get/filter/',views.freq_sort, name='filter'),
    path('get/graph/<slug:data_id>/<slug:mt_name>/', Meas_graph.as_view(), name = 'graph'),
    path('get/meastype_info/<slug:mt_name>/<slug:ssi_info_name>/<slug:id_measure>/<slug:valid>/',Check_valid.as_view(), name = 'valid'),
    path('get/key/',views.key_create, name='key'),
    path('get/cr_measure/',views.create_measure, name='create_measure'),
    path('operator/',views.create_operator, name='op'),
    path('payload/',views.create_payload, name='pay_load'),
    path('key_list/', Keys_lists.as_view(), name = 'keys_list'),
    path('get/c_pdf/<slug:name_ssi>/<slug:id_data>/<slug:name_measure>/', Create_PDF.as_view(), name = 'create_pdf'),
    path('key_rem/<slug:id_key>/', Remove_keys.as_view(), name = 'remove_key'),
    path('type_rem/<slug:id_type>/', Remove_type.as_view(), name = 'remove_measure_type'),
    path('edit_key/<int:id_edit_key>/',views.edit_key, name='ed_key'),
    path('download/<slug:ssi>/<slug:type_m>/',views.downloadPDF, name='download_pdf'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
import socket

class Keys(models.Model):# Параметры для передачи в ВАЦ
    namber_of_points_for_smoothing=models.IntegerField(null=True,blank=True,default=201, verbose_name="Количество точек сглаживания")
    input_power=models.IntegerField(null=True,blank=True,verbose_name="Входная мощность")
    input_power_first=models.IntegerField(null=True,blank=True,verbose_name="Входная мощность начальная")
    input_power_last=models.IntegerField(null=True,blank=True,verbose_name="Входная мощность конечная")
    width_filter=models.IntegerField(null=True,blank=True,verbose_name="Ширина фильтра ПЧ")
    namber_of_points_for_averaging=models.IntegerField(null=True,blank=True,default=201, verbose_name="Количество точек")
    def __str__(self):
        return f'Кол-во точек сгл:{self.namber_of_points_for_smoothing}; Вх_P:{self.input_power}; Вх_Pнач:{self.input_power_first}; Вх_Pкон:{self.input_power_last}; Ширина_ПЧ:{self.width_filter}; Кол-во_точек:{self.namber_of_points_for_averaging}'

class SpaceCraft(models.Model):
    name = models.CharField(("Наименование КА"), max_length=50)
    def __str__(self):
        return self.id.__str__()+'.'+self.name

class PayLoad(models.Model):
    name = models.CharField(("Наименование РТР"), max_length=50)
    spacecraft = models.ForeignKey("SpaceCraft", verbose_name=("КА"), on_delete=models.CASCADE)
    def __str__(self):
        return self.name

#Менеджер моделей, для FreqRange
class FreqRangeManager(models.Manager):
    def get_queryset(self,freq):
        return super(FreqRangeManager, self).get_queryset().filter(name=freq)

class SSIManager(models.Manager):
    def get_queryset(self,freq):
        return super(SSIManager, self).get_queryset().filter(freqrange__name=freq)

class MeasureType(models.Model):                         #Тип измерерия АЧХ, НГВЗ, точка насыщения, АМ-АМ
    name = models.CharField(max_length=50,verbose_name="Тип измерения")
    key=models.ForeignKey("Keys", verbose_name=("Ключи"), on_delete=models.CASCADE, related_name = 'keys')
    def __str__(self):
        return self.name

class SSI(models.Model):                                    #Конфигурации
    name = models.CharField('Имя SSI',max_length=50, unique=True)                  
    input_frequency = models.FloatField('Входная частота')
    output_frequency = models.FloatField('Выходная частота')
    band_frequency = models.FloatField('Полоса частот')
    available_meas= models.ManyToManyField(MeasureType, related_name='ssi',verbose_name="Тип измерения")
    pay_load=models.ForeignKey(PayLoad,  null=True,blank=True, on_delete = models.CASCADE,related_name = 'pay_load_ssi',verbose_name="Полезная нагрузка")
    objects=models.Manager()
    ssi_manager=SSIManager()
    def __str__(self):
        return self.name

class FreqRange(models.Model):
    input_range = models.CharField(("Входной диапазон"), max_length=50)
    output_range = models.CharField(("Выходной диапазон"), max_length=50)
    ssi_element =  models.ForeignKey(SSI, on_delete = models.CASCADE,related_name = 'freqrange')
    name=models.CharField(("Имя диапазона"), max_length=50)
    objects=models.Manager()
    custom_manager=FreqRangeManager()
    def __str__(self):
        return f'{str(self.input_range)}/{str(self.output_range)}'

class Measure_que(models.Model):                            # Класс очереди
    date_time = models.DateTimeField(auto_now_add = True)
    ssi = models.ForeignKey(SSI, on_delete = models.CASCADE, verbose_name="Имя SSI")
    meastype = models.ForeignKey(MeasureType, on_delete = models.CASCADE,verbose_name="Тип измерения")
    def __str__(self):
        return 'Имя SSI: {}, Тип измерения: {}, Время измерения: {}'.format(self.ssi, self.meastype, self.date_time)

class Measure(models.Model): 
    class Meta:
        permissions = (("make_measures", "проводит измерения"),)                                 #Класс, собирающий информацию о имени SSI и типе измерения в нем для передачи этой информации в AcceptData
    time = models.DateTimeField(auto_now_add = True)
    ssi = models.ForeignKey(SSI, on_delete = models.CASCADE,related_name='meas', verbose_name="Имя SSI")
    mea = models.ForeignKey(MeasureType, on_delete = models.CASCADE,related_name = 'measure_type',verbose_name="Тип измерения")
    def __str__(self):
        return 'Имя SSI: {}, Тип измерения: {}'.format(self.ssi, self.mea)

class AcceptData(models.Model):                            # X-Y данные
    xy = models.TextField('Полученные данные x,y')
    measurement_data = models.ForeignKey(Measure, on_delete = models.CASCADE,related_name = 'm')
    isvalid=models.IntegerField(default=0, verbose_name="Валидность")
    realism=models.BooleanField(default=0, verbose_name="Реальность измерений:")
    def __str__(self):
        return ' Измерения: {}'.format(self.measurement_data)

class Operator(models.Model):
    firstname = models.CharField(default="Александр", verbose_name="Имя оператора", max_length=50)
    lastname = models.CharField(default="Иванов", verbose_name="Фамилия оператора", max_length=50)
    accept_data=models.ForeignKey(AcceptData, null=True,blank=True, on_delete = models.CASCADE, related_name = 'operator_ad',verbose_name="Проведенные измерения")
    def __str__(self):
        return f'{self.firstname} {self.lastname}'

app/forms.py
from django import forms
from .models import SSI,Operator,SpaceCraft,PayLoad,Keys,MeasureType
from django.contrib.auth.forms import UserCreationForm

'''
Класс отвечает за создание формы, где model = SSI показывает какой класс будет использоваться для создания формы,
fields говорит, какие поля использовать для этого.
'''
CHOICES = (
    ('offline', 'Использовать offline сервер'),
    ('real', 'Использовать векторный анализатор цепей'),
)
CHOICES_VALID = (
    ('valid', 'Измерения проведены'),
    ('invalid', 'Измерения отсутствуют'),
    ('not_chosen', 'Не проверено!'),
)

class SSIform(forms.ModelForm):
    class Meta:
        model = SSI
        fields = ('name', 'input_frequency','output_frequency','band_frequency','available_meas', 'pay_load')

class Keysform(forms.ModelForm):
    class Meta:
        model = Keys
        fields = ('namber_of_points_for_smoothing','input_power','input_power_first', 'input_power_last','width_filter','namber_of_points_for_averaging')

class MeasureTypeform(forms.ModelForm):
    class Meta:
        model = MeasureType
        fields = ('name','key')
        widgets = { 'key' : forms.Select(attrs={'size':'1'}) }

class Operatorform(forms.ModelForm):
    class Meta:
        model = Operator
        fields = ('firstname', 'lastname','accept_data')

class SpaceCraftform(forms.ModelForm):
    class Meta:
        model = SpaceCraft
        fields = ('name',)

class PayLoadform(forms.ModelForm):
    class Meta:
        model = PayLoad
        fields = ('name','spacecraft')

class Formfilter(forms.Form):
    choice=forms.CharField(widget=forms.Select())

class Choose_device(forms.Form):
    choose=forms.ChoiceField(widget=forms.RadioSelect(), choices=CHOICES, initial='real')

# class UploadFileForm(forms.Form):
#     file = forms.FileField()

# class Valid_maesures(forms.Form):
#     valid=forms.ChoiceField(widget=forms.RadioSelect(), choices=CHOICES_VALID, initial='not_chosen')

app/templates/app/Keys.html
{% extends 'app/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Список созданных ключей:</th>
                        <th>Действия:</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in key %}
                        <tr>
                            <td>
                                <div>{{i}}</div>
                            </td>
                            <td>
                                <a href={% url 'remove_key' i.id %} class="btn btn-danger">Удалить ключ</a>
                            </tg>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/app/base.html
{% load staticfiles %}

<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>view_1</title>
        
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'main.css' %}">
        <script src="{% static 'js/Chart.min.js' %}"></script>
        <script src="{% static 'js/axios.min.js' %}"></script>
    </head>
    <body>
        <div class="container-fluid">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex justify-content-between ">
                    <img src="{% static 'images/python.svg' %}" alt="logo" class='img-fluid' width='100' height='100'>
                    <nav class="nav">
                        <div class="row">
                            <div class="col-md-2">
                                <li class="nav-item"><a class="nav-link active" href="{% url 'base_list' %}">Home</a></li>
                            </div>
                            <div class="col-md-3">
                                <li class="nav-item"><a class="nav-link active" href={% url 'ssi_list' %}>Measurements</a></li>
                            </div>
                            <div class="col-md-4">
                                <li class="nav-item"><a class="nav-link active" href={% url 'create' %}>Create config</a></li>
                            </div>
                            <div class="col-md-3">
                                <li class="nav-item"><a class="nav-link active" href={% url 'help_list' %}>Help</a></li>
                            </div>
                        </div>
                    </nav>
                    {% if user.is_authenticated %}
                        <nav class="nav">
                            <div class="col-md-3">
                                <li class="nav-item"><a class="nav-link active" href='http://127.0.0.1:8000/admin/'>Admin</a></li>
                            </div>
                        </nav>
                    {% else %}
                    {% endif %} 
                    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
                        {% if user.is_authenticated %}
                            <li id ='info'class="badge badge-success">Пользователь: {{ user.get_username }}</li>
                            <a id ='btninfo' href="{% url 'logout'%}?next={{request.path}}" class="btn btn-info">Logout</a>  
                        {% else %}
                            <a id ='btninfo1' href="{% url 'login'%}?next={{request.path}}" type="button" class="btn btn-info">Login</a>
                        {% endif %} 
                    </ul>
                    <nav class="nav ">
                    </nav>
                </nav>
                {% block content %}
                {% comment %} <p>Информацию о способах проведения измерений можно получить в разделе Help!</p> {% endcomment %}
                <div class="jumbotron">
                    <h1 class="display-3">Вход выполнен!</h1>
                    <p class="lead">Для проведения измерений необходимо заполнить форму, представленную ниже.</p>
                    <hr class="my-2">
                    <div class="row d-flex justify-content-center">
                        <form action = "{% url 'op' %}"  method="POST" class="post-form " > {% csrf_token %}
                            {% comment %} <div class="col-md ">
                                <p>В форме "Оператор" необходимо заполнить имя и фамилию того, кто будет проводить измерения.</p> {% endcomment %}
                                {% comment %} {{operator}} {% endcomment %}
                                {% comment %} <div><label for="id_firstname">Имя оператора:</label></div>
                                <div>{{operator.firstname}}</div>
                                <div><label for="id_lastname">Фамилия оператора:</label></div>
                                <div>{{operator.lastname}}</div>
                            </div> {% endcomment %}
                            <div class="col-md">
                                <p>В форме "Наименование КА" нужно указать название КА, для которого будут проводися измерения.</p>
                                {% comment %} {{spacecraft}} {% endcomment %}
                                <div><label for="id_name">Наименование КА:</label></div>
                                <div>{{spacecraft.name}}</div>
                                <p class="lead">
                                <div><div><button id = "btn1" type="submit" class="save btn btn-primary btn-sm">Отправить данные</button></div></div>
                                </p>
                            </div>
                        </form>
                        <form action = "{% url 'pay_load' %}"  method="POST" class="post-form " > {% csrf_token %}
                            <div class="col-md">
                                <p>В форме "Наименование РТР" нужно указать название ПН.</p>
                                {% comment %} {{payload}} {% endcomment %}
                                <div><label for="id_name">Наименование РТР:</label></div>
                                <div>{{payload.name}}</div>
                                <div><label for="id_spacecraft">КА:</label></div>
                                <div>{{payload.spacecraft}}</div>
                                <p class="lead">
                                    <div><button id = "btn1" type="submit" class="save btn btn-primary btn-sm">Отправить данные</button></div>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
                {% endblock%}

        </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

app/templates/app/create_config.html
{% extends 'app/base.html' %}
{% block content %}

<div class="container-fluid">
    <div  id="row-in_createconfig1" class="row ">
        <div class="col-md-4 ">
            <form id = "form_key1" action = "{% url 'key' %}" method="POST" class="post-form d-flex justify-content-start" >{% csrf_token %}
                <div class="col-6 ">
                    <div><label for="id_input_power">Входная мощность:</label></div>
                    <div>{{keys_form.input_power}}</div>

                    <div><label for="id_input_power_first">Входная мощность начальная:</label></div>
                    <div>{{keys_form.input_power_first}}</div>

                    <div><label for="id_input_power_last">Входная мощность конечная:</label></div>
                    <div>{{keys_form.input_power_last}}</div>
                    <button id = "btn1" type="submit" class="save btn btn-primary">Добавить ключ</button>
                </div>
                <div class="col-6 ">
                    <div><label for="id_namber_of_points_for_smoothing">Количество точек сглаживания:</label></div>
                    <div>{{keys_form.namber_of_points_for_smoothing}}</div>

                    <div><label for="id_width_filter">Ширина фильтра ПЧ:</label></div>
                    <div>{{keys_form.width_filter}}</div>
                    
                    <div><label for="id_namber_of_points_for_averaging">Количество точек:</label></div>
                    <div>{{keys_form.namber_of_points_for_averaging}}</div>
                </div>
            </form>
        </div>
        <div class="col-md-8 d-flex justify-content-around">
            <div class="col-3">
                <form  id ="form_table_meas"  action = "{% url 'create_measure' %}" method="POST" class="post-form">{% csrf_token %}
                    <div>
                        <label for="id_name">Тип измерения:</label>
                    </div>
                    <div>
                        <input type="text" name="name" maxlength="50" required="" id="id_name">
                    </div>
                    <div>
                        <label for="id_key">Ключи:</label>
                    </div>
                    <div>
                        {{measuretype_form.key}}
                    </div>
                    <div>
                        <button id = "btn1" type="submit" class="save btn btn-primary">Добавить тип</button>
                        {% comment %} <div><a href="#!">Список ключей</a> </div> {% endcomment %}
                    </div>
                </form>
            </div>
            <div class="col-md-9">
                <table class="table table-bordered">
                    <thead class="thead-light">
                        <tr>
                            <th>Тип:</th>
                            <th>Ключи: <a href="{% url 'keys_list' %}">Полный список созданных ключей</a></th>
                            <th>Действия:</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for m in measure_type_data %}
                            <tr>
                                <td>
                                    <div>{{m}}</div> 
                                </td>
                                <td>
                                    {% comment %} {% for k in key_data%}
                                        <div>{{k}}</div>
                                    {% endfor %} {% endcomment %}
                                    {{m.key}}
                                </td>
                                <td>
                                    <div><a href={% url 'ed_key' m.key.id %} class="btn btn-primary btn-sm">Изменить ключ</a></div> 
                                    {% comment %} <a id= "del" href={% url 'remove_key' m.key.id %} class="btn btn-danger btn-sm">Удалить ключ</a> {% endcomment %}
                                    <a id= "del" href={% url 'remove_measure_type' m.id %} class="btn btn-danger btn-sm">Удалить тип</a>    
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="row1" class="row">
        <form id = "form_createmea1" method="POST" class="post-form d-flex justify-content-around">{% csrf_token %}
            <div class="col-md-4">
                <label class="d-flex flex-wrap align-content-start" for="id_name">Имя SSI:</label>
                <input type="text" name="name" maxlength="50" required="" id="id_name" placeholder="SSI_1">                                    
                <label for="id_input_frequency">Входная частота,ГГц:</label>
                <input type="number" name="input_frequency" required="" id="id_input_frequency" placeholder="28" step="0.001">
                <label for="id_pay_load">ПН:</label>
                <div id='div1'>{{form.pay_load}} </div>
                <button id = "btn1" type="submit" class="save btn btn-primary">Добавить SSI</button>  
            </div>       
            <div class="col-md-4">
                <label for="id_band_frequency">Полоса частот,МГц:</label>
                <input type="number" name="band_frequency" required="" id="id_band_frequency" placeholder="34" step="0.001">                
                <label for="id_output_frequency">Выходная частота,ГГц:</label>
                <input type="number" name="output_frequency" required="" id="id_output_frequency" placeholder="78" step="0.001">
            </div>
            <div class="col-md-2">
                <label for="id_available_meas">Тип измерения:</label>
                <div id='div1'>{{ form.available_meas}}</div>
            </div>            
        </form>
        <div class="col-md-7 " >    
            <table class="table table-bordered">
                <thead class="thead-light"> 
                    <tr>
                        <th>Имя SSI</th>
                        <th>Входная частота, ГГц</th>
                        <th>Выходная частота, ГГц</th>
                        <th>Полоса частот, МГц</th>
                        <th>Выбранные измерения</th>
                        <th>Частотный диапазон</th>
                        <th>ПН</th>
                        <th>КА</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in Freqmodel %}
                        <tr>
                            <td>{{i.ssi_element.name}}</td>
                            <td>{{i.ssi_element.input_frequency}}</td>
                            <td>{{i.ssi_element.output_frequency}}</td>
                            <td>{{i.ssi_element.band_frequency}}</td>
                            <td>
                                {% for meas in i.ssi_element.available_meas.all %}
                                    {{meas.name}}
                                {% endfor %}
                            </td>
                            <td>{{i.name}}</td>
                            <td>{{i.ssi_element.pay_load.name}}</td>
                            <td>{{i.ssi_element.pay_load.spacecraft}}</td>
                            <td >
                                <div><a href={% url 'edit_ssi' i.ssi_element.id %} class="btn btn-primary btn-sm">Изменить SSI</a></div> 
                                <a id="del" href={% url 'ssi_remove_ssilist' i.ssi_element.id %} class="btn btn-danger btn-sm">Удалить SSI</a>
                            </td> 
                            {% comment %} Доступ через SSI к SSI 
                            <td>{{s.input_frequency}}</td>
                            <td>{{s.output_frequency}}</td>
                            <td>{{s.band_frequency}}</td>                                      
                            <td>
                                {% for meas in s.available_meas.all %}
                                    {{meas.name}}
                                {% endfor %}
                            </td>
                            <td>{{s.freqrange.all.get}}</td>  
                            <td><a href={% url 'ssi_remove_ssilist' s.id %} class="btn btn-danger">Delete</a></td> {% endcomment %}
                        </tr>
                    {% endfor %}
                </tbody> 
            </table>         
        </div>
    </div>
</div>
{% endblock content %}

app/templates/app/edit_key.html
{% extends 'app/base.html' %}
{% block content %}

<div class="container-fluid">
    <div id="row-in_createconfig1" class="row d-flex justify-content-between">
        <div class="col-6 ">
            <form method="POST" class="d-flex justify-content-end">
                {% csrf_token %}
                <div class="col-6 ">
                    <p>
                        <label>Введите количество точек для сглаживания:</label><br>
                        <input type="text" name="namber_of_points_for_smoothing" value="{{key.namber_of_points_for_smoothing}}" />
                    </p>
                    <p>
                        <label>Введите входную мощность, дБ:</label><br>
                        <input type="number" name="input_power" value="{{key.input_power}}" />
                    </p>
                    <p>
                        <label>Введите входную начальную мощность, дБ:</label><br>
                        <input type="number" name="input_power_first" value="{{key.input_power_first}}" />
                    </p>
                    <button type="submit" class="save btn btn-success">Сохранить</button>
                </div>
                <div class="col-6 ">
                    <p>
                        <label>Введите входную конечную мощность, дБ:</label><br>
                        <input type="number" name="input_power_last" value="{{key.input_power_last}}" />
                    </p>
                    <p>
                        <label>Введите ширину фильтра ПЧ:</label><br>
                        <input type="number" name="width_filter" value="{{key.width_filter}}" />
                    </p>
                    <p>
                        <label>Введите количество точек сглаживания:</label><br>
                        <input type="number" name="namber_of_points_for_averaging" value="{{key.namber_of_points_for_averaging}}" />
                    </p>
                </div>
            </form>
        </div>
        <div class="col-6">
            <table class="table table-bordered">
                <thead  class="thead-light" >
                    <tr>
                        <th>Редактируемый ключ:</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{key}}</td>
                    </tr>
                </tbody>
            </table>
            <a href={% url 'keys_list' %} class="btn btn-primary btn-sm">Вернуться к списку ключей</a>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/app/editssi.html
{% extends 'app/base.html' %}
{% block content %}

<div class="container-fluid">
    <div id="row-in_createconfig1" class="row d-flex justify-content-between">
        <div class="col-5 ">
            <form method="POST" class="d-flex justify-content-end">
                {% csrf_token %}
                <div class="col-5 ">
                    <p>
                        <label>Имя SSI:</label><br>
                        <input type="text" name="name" value="{{ssi.name}}" />
                    </p>
                    <p>
                        <label>Входная частота, ГГц:</label><br>
                        <input type="number" name="input_frequency" value="{{ssi.input_frequency}}" />
                    </p>
                    <p>
                        <label>Выходная частота, ГГц:</label><br>
                        <input type="number" name="output_frequency" value="{{ssi.output_frequency}}" />
                    </p>
                    <button type="submit" class="save btn btn-success">Сохранить</button>
                </div>
                <div class="col-6 ">
                    <p>
                        <label>Полоса, МГц:</label><br>
                        <input type="number" name="band_frequency" value="{{ssi.band_frequency}}" />
                    </p>
                    {% comment %} <p>
                        <label>Доступные измерения:</label><br>

                        <select name="available_meas" required="" id="id_available_meas" multiple="">
                            {% for i in  mea_type%}
                                <option value={{i}}> {{i}} </option>
                            {% endfor %}
                        </select>  {% endcomment %}
                        {% comment %} <div id='div1'>{{ ssi_form.available_meas}}</div>
                    </p>
                    {% comment %} <p>
                        <label>Полезная нагрузка:</label><br>
                        <input type="text" name="pay_load" value="{{ssi.pay_load}}" />
                    </p> {% endcomment %}
                </div>
            </form>
        </div>
        <div class="col-7">
            <table class="table table-bordered">
                <thead  class="thead-light" >
                    <tr>
                        <th>Имя SSI</th>
                        <th>Входная частота, ГГц</th>
                        <th>Выходная частота, ГГц</th>
                        <th>Полоса частот, МГц</th>
                        <th>Выбранные измерения</th>
                        <th>Частотный диапазон</th>
                        <th>ПН</th>
                        <th>КА</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ssi.name}}</td>
                        <td>{{ssi.input_frequency}}</td>
                        <td>{{ssi.output_frequency}}</td>
                        <td>{{ssi.band_frequency}}</td>
                        <td>
                        {% for meas in ssi.available_meas.all %}
                            {{meas.name}}
                        {% endfor %}
                        </td>
                        <td>{{ssi.freqrange.get.name}}</td>
                        <td>{{ssi.pay_load}}</td>
                        <td>{{ssi.pay_load.spacecraft}}</td>
                    </tr>
                </tbody>
            </table>
            <a href={% url 'create' %} class="btn btn-primary btn-sm">Вернуться к списку SSI</a>
        </div>
    </div>
</div>

{% endblock content %}